### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by FlorianWendelborn** [macfire10/react-shortcuts-hook#1]
Would be great if this library could include type definitions. Easiest way to accomplish this (and also allowing you to get rid of babel, etc.) would be to just convert it to TypeScript, although I can understand it if you don’t want to use it.

Alternatively, a quite tiny `types.d.ts` would do. 🙂

**Comment by macfire10** [comment]
Hello, thanks for your input!

I support the idea, but since I don't have that much experience with TypeScript, I can't really predict if this change will affect the bundle size. I will dedicate my time into researching this sometime next week :)

**Comment by FlorianWendelborn** [comment]
@macfire10 the `types.d.ts` will literally have 0 impact on the bundle size. It’s development-only. Rewriting in TypeScript possibly slightly changes the output due to a different compiler being used (babel vs tsc), so it may or may not increase/decrease the size.

**Comment by macfire10** [comment]
> @macfire10 the `types.d.ts` will literally have 0 impact on the bundle size. It’s development-only. Rewriting in TypeScript possibly slightly changes the output due to a different compiler being used (babel vs tsc), so it may or may not increase/decrease the size.

Sorry for being much more late than I should have! I've converted this library to TS, could you take a look at the code?

**Comment by macfire10** [comment]
Closed.

**Comment by FlorianWendelborn** [comment]
@macfire10 LGTM besides `String` which should be used in the lower-case form.

See <https://stackoverflow.com/questions/14727044/typescript-difference-between-string-and-string>
