### ISSUE TITLE
Keys are not release on window blur

### ISSUE THREAD

**Issue by Rafatcb** [macfire10/react-shortcuts-hook#11]
I'm testing it in Electron, but this problem happens in Chrome too (you can try it in the [project demo](https://codesandbox.io/s/basic-example-g6fnu?fontsize=14&hidenavigation=1&theme=dark&file=/src/App.js)).

If your shortcut contains `Ctrl` or `Alt` and you use `Ctrl`+`Tab` or `Alt`+`Tab` (Windows shortcuts), the project tab/window will loose focus. Yet, when focusing the tab/window again and pressing a key that completes the shortcut (e.g. `K`), it  is activated.

It could be fixed with a blur listener:

```js
// ...hook code

function onWindowBlur(): void {
  pressedKeys.clear();
}

useEffect(() => {
  window.addEventListener("keydown", onKeyPressed);
  window.addEventListener("keyup", onKeyUp);
  window.addEventListener("blur", onWindowBlur);

  return () => {
    window.removeEventListener("keydown", onKeyPressed);
    window.removeEventListener("keyup", onKeyUp);
    window.removeEventListener("blur", onWindowBlur);
  };
}, [memoizedCallback]);

// ...hook code
```

**Comment by macfire10** [comment]
Hey!

This makes sense to me, thank you for making a PR.
